In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv('daily_data.csv')

In [6]:
data

,Unnamed: 0,date,co,no,no2,o3,so2,pm2_5,pm10,nh3,AQI
0,0,2023-07-31,209.954000,0.010000,3.178000,27.036000,4.278000,16.880000,32.188000,0.484000,2.000000
1,1,2023-08-01,240.673750,0.469583,5.077500,30.487917,6.204583,16.182917,31.093333,1.383750,2.000000
2,2,2023-08-02,233.302917,0.206667,4.759583,31.665000,5.604167,15.512083,29.088333,1.151250,2.000000
3,3,2023-08-03,228.504167,0.344167,4.325000,26.352083,5.249167,18.022917,37.946250,1.111250,2.083333
4,4,2023-08-04,234.900833,0.182500,5.064167,28.662083,5.599167,19.547500,52.362083,1.168333,2.541667
5,5,2023-08-05,220.854167,0.243333,3.981250,31.530417,4.779167,20.863750,48.510417,0.887917,2.541667
6,6,2023-08-06,225.165417,0.383333,4.073333,30.204583,5.048750,17.982500,34.882500,1.064583,2.000000
7,7,2023-08-07,227.669583,0.273333,4.894167,30.412083,5.813750,17.672500,39.396667,1.266667,2.000000
8,8,2023-08-08,241.577500,0.559583,5.431667,33.080833,6.708333,18.870833,39.401667,1.547917,2.000000
9,9,2023-08-09,268.001667,0.343333,7.549583,28.282500,8.620000,18.135417,38.341250,1.853333,2.125000
10,10,2023-08-10,380.237917,1.898333,10.673333,29.019583,11.675417,21.114583,40.473333,4.075833,2.291667
11,11,2023-08-11,305.969583,1.486667,8.867500,33.631667,11.866250,17.599167,39.205417,2.870417,2.000000
12,12,2023-08-12,264.665000,0.436667,7.730833,29.072083,9.124583,12.556667,21.842917,1.840000,2.000000
13,13,2023-08-13,230.521250,0.396250,4.275000,33.200417,5.496250,12.399167,27.515000,1.096667,2.000000
14,14,2023-08-14,248.879583,0.418333,5.159583,34.764583,6.348333,11.323333,36.997917,1.513750,2.000000
15,15,2023-08-15,259.936667,0.632083,7.123333,29.221250,9.029167,12.960000,31.255000,1.846667,2.000000
16,16,2023-08-16,283.439167,1.454583,8.764167,27.179583,12.248333,15.339583,37.127083,2.610833,2.000000
17,17,2023-08-17,284.275000,1.059583,10.227917,20.944583,12.580833,14.174167,25.691250,2.438333,1.958333
18,18,2023-08-18,293.175000,1.552917,10.468333,18.946250,13.804167,12.907500,22.570000,2.630833,1.833333
19,19,2023-08-19,250.200417,0.466250,7.791250,24.788750,9.118750,12.213333,20.277083,1.582917,1.791667
20,20,2023-08-20,289.419583,1.243750,10.575000,21.546667,12.542083,15.152083,25.080833,2.612083,2.000000
21,21,2023-08-21,406.105833,2.461250,13.990833,17.322500,16.247083,20.245417,35.679167,5.007500,2.208333
22,22,2023-08-22,330.447917,1.708333,12.312917,16.637083,15.532083,14.654167,22.877083,3.758333,2.000000
23,23,2023-08-23,284.969583,1.050000,7.843333,18.257083,9.778750,10.484167,21.222917,2.678333,1.791667
24,24,2023-08-24,249.435417,0.684167,6.832083,20.809583,8.389167,8.153333,12.100417,1.769583,1.125000
25,25,2023-08-25,260.492500,0.818333,6.795833,22.836667,8.002500,10.720833,15.413333,1.888750,1.625000
26,26,2023-08-26,216.613333,0.538333,5.114583,24.855417,6.582500,8.959167,13.422917,1.307083,1.208333
27,27,2023-08-27,295.122500,0.970417,9.360000,20.395417,10.860417,12.866250,18.107083,2.879167,1.666667
28,28,2023-08-28,287.681250,1.607083,9.760417,20.261667,14.046667,11.516667,16.053750,2.701250,1.916667
29,29,2023-08-29,746.011250,6.746250,23.751250,23.777083,30.343750,40.992917,56.897917,12.244167,3.041667
30,30,2023-08-30,1479.507500,28.421250,26.060833,20.583333,52.810000,86.495833,127.492083,18.841667,4.125000
31,31,2023-08-31,1970.216316,46.305263,33.560526,29.422632,80.235789,139.639474,192.201053,22.536316,4.263158

In [7]:
X = data[['co','no','no2','o3','so2','pm2_5','pm10','nh3']]

In [8]:
y = data['AQI']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=0)

In [14]:
# data split into training and test set
#now using a linear regression model

In [16]:
train_data = X_train.join(y_train)

In [27]:
# linear regressor
from sklearn.linear_model import LinearRegression

In [28]:
reg = LinearRegression()

In [29]:
reg.fit(X_train,y_train)

LinearRegression()

In [52]:
reg.score(X_test,y_test)

0.3774763388286346

In [31]:
reg.predict(X_test)

array([2.23217396, 1.776967  , 2.49774698, 1.95280197, 2.05936822,
       2.28000275, 1.49331538, 1.31539572])

In [32]:
y_test

11    2.000000
22    2.000000
10    2.291667
2     2.000000
16    2.000000
14    2.000000
28    1.916667
26    1.208333
Name: AQI, dtype: float64

In [39]:
result = {'predictions':reg.predict(X_test),
          'actual_values':y_test
         }

In [44]:
result = pd.DataFrame(result)
result['diff'] = result['predictions']-result['actual_values']
result['error'] = result[] 
result

    predictions  actual_values      diff
11     2.232174       2.000000  0.232174
22     1.776967       2.000000 -0.223033
10     2.497747       2.291667  0.206080
2      1.952802       2.000000 -0.047198
16     2.059368       2.000000  0.059368
14     2.280003       2.000000  0.280003
28     1.493315       1.916667 -0.423351
26     1.315396       1.208333  0.107062

In [61]:
from sklearn.metrics import r2_score

In [63]:
r2_score(y_test,reg.predict(X_test),sample_weight=None)

0.3774763388286346